# Generated by Django 5.2.7 on 2025-11-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('advertisement_video', models.FileField(blank=True, null=True, upload_to='about_us/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Media',
                'verbose_name_plural': 'About Us Media',
            },
        ),
    ]
