# Generated by Django 5.2.7 on 2025-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
