# Generated by Django 5.2.7 on 2025-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_location_lat_alter_item_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('archived', 'Archived')], default='unclaimed', max_length=20),
        ),
    ]
