# Generated by Django 5.2.7 on 2025-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claim_proof',
            field=models.ImageField(blank=True, null=True, upload_to='claim_proofs/'),
        ),
    ]
