# Generated by Django 5.2.7 on 2025-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claimed_by_username',
            field=models.CharField(blank=True, help_text='Username of person who returned/claimed the item', max_length=150),
        ),
    ]
