# Generated by Django 5.2.7 on 2025-10-12 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_name'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='items.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_received', to=settings.AUTH_USER_MODEL)),
                ('returner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_returned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
