# Generated by Django 5.2.7 on 2025-10-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_approved_at_item_approved_by_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_notifications', to='items.item'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_notifications', to='items.itemmatch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('item_approved', 'Item Approved'), ('item_rejected', 'Item Rejected'), ('match_found', 'Potential Match Found'), ('item_claimed', 'Item Claimed'), ('message_received', 'New Message'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
